table Customers_lookup
	lineageTag: f6f0aad3-9444-4755-8b15-b9a9976dbe49

	column customer_id
		dataType: string
		lineageTag: 5fd44e14-a10c-4948-8964-8bd0c1a7e8a7
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_zip_code_prefix
		dataType: int64
		formatString: 0
		lineageTag: d0399aa4-de4c-46cb-9e84-e73859aef0ea
		dataCategory: PostalCode
		summarizeBy: sum
		sourceColumn: customer_zip_code_prefix

		annotation SummarizationSetBy = Automatic

	column customer_city
		dataType: string
		lineageTag: 7d727c5e-f97e-4fe4-aac9-be9d3898a143
		dataCategory: City
		summarizeBy: none
		sourceColumn: customer_city

		annotation SummarizationSetBy = Automatic

	column customer_state
		dataType: string
		lineageTag: 514146e7-50fb-4cb7-b53a-67cbef8fcacc
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: customer_state

		annotation SummarizationSetBy = Automatic

	column Country = "Brazil"
		lineageTag: ae5d02d4-4dce-48c0-ac4a-d3301ed73ee9
		dataCategory: County
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Customers_lookup = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\NC\OneDrive\Desktop\Nexusgoods store capstone\Nexusgoods_customers_dataset .csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"customer_id", type text}, {"customer_zip_code_prefix", Int64.Type}, {"customer_city", type text}, {"customer_state", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

