table Order_items
	lineageTag: 6b627a1a-d75a-49f2-a404-b5535c56e9a0

	measure 'Total Unique Orders' = CALCULATE(DISTINCTCOUNT(Order_items[order_id]),NOT(ISBLANK(Order_items[Delivery Status])))
		formatString: 0
		lineageTag: 59b9e150-4224-492f-8d73-2e90bbc5b106

	measure 'Total Delivered Orders' = CALCULATE(DISTINCTCOUNT(Order_items[order_id]),Order_items[Delivery Status]="Delayed")
		formatString: 0
		lineageTag: cfbf6e4e-3263-4613-a28d-182d83d7e304

	measure '% Orders Delayed' = [Total Delivered Orders]/[Total Unique Orders]
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: b2d9fbd6-f774-401a-8375-41e60be676d7

	column order_id
		dataType: string
		lineageTag: 218f47bb-4e63-441a-9a08-10c6216d6fd7
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column order_item_id
		dataType: int64
		formatString: 0
		lineageTag: e5dbc166-db80-4ee9-b544-2dfabc6e87e2
		summarizeBy: sum
		sourceColumn: order_item_id

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: string
		lineageTag: 11f49b2b-e87f-41a4-ba25-586768499462
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column seller_id
		dataType: string
		lineageTag: bfb3cdb3-5b90-4e10-a38c-350055fcd452
		summarizeBy: none
		sourceColumn: seller_id

		annotation SummarizationSetBy = Automatic

	column shipping_limit_date
		dataType: dateTime
		formatString: General Date
		lineageTag: 60741dcb-c547-4545-81f5-f41811e3267b
		summarizeBy: none
		sourceColumn: shipping_limit_date

		variation Variation
			isDefault
			relationship: 2ed0b92a-938f-439f-b32f-02d37773da87
			defaultHierarchy: LocalDateTable_2c012bf2-d200-4be6-a0b3-eede0a09e652.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column price
		dataType: double
		lineageTag: a1c00226-65fd-4136-86cd-dff0b43fd924
		summarizeBy: sum
		sourceColumn: price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column freight_value
		dataType: double
		lineageTag: ffb6f916-1b25-48e9-93bc-2347cd2ccec4
		summarizeBy: sum
		sourceColumn: freight_value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Order Value'
		dataType: double
		formatString: "€"\ #,0.00;-"€"\ #,0.00;"€"\ #,0.00
		lineageTag: a508b5df-89f7-4141-9e79-0f1c694469c9
		summarizeBy: sum
		sourceColumn: Total Order Value

		annotation SummarizationSetBy = Automatic

	column 'Products_lookup.Category Name'
		dataType: string
		lineageTag: 4d33fcae-5244-43f1-8c6b-e77785f37411
		summarizeBy: none
		sourceColumn: Products_lookup.Category Name

		annotation SummarizationSetBy = Automatic

	column 'Delivery Status'
		dataType: string
		lineageTag: 695399dd-5eae-429a-9f59-72fccc9320f1
		summarizeBy: none
		sourceColumn: Delivery Status

		annotation SummarizationSetBy = Automatic

	column 'Order_reviews_lookup.Average Rating'
		dataType: double
		lineageTag: 9e867deb-0781-4829-b6db-ad94df53ee3f
		summarizeBy: sum
		sourceColumn: Order_reviews_lookup.Average Rating

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Order_items = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\NC\OneDrive\Desktop\Nexusgoods store capstone\Nexusgoods_order_items_dataset.csv"),[Delimiter=",", Columns=7, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"order_id", type text}, {"order_item_id", Int64.Type}, {"product_id", type text}, {"seller_id", type text}, {"shipping_limit_date", type datetime}, {"price", type number}, {"freight_value", type number}}),
				    #"Inserted Addition" = Table.AddColumn(#"Changed Type", "Addition", each [price] + [freight_value], type number),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Addition",{{"Addition", "Total Order Value"}}),
				    #"Merged Queries" = Table.NestedJoin(#"Renamed Columns", {"product_id"}, Products_lookup, {"product_id"}, "Products_lookup", JoinKind.LeftOuter),
				    #"Expanded Products_lookup" = Table.ExpandTableColumn(#"Merged Queries", "Products_lookup", {"Category Name"}, {"Products_lookup.Category Name"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Expanded Products_lookup", {"order_id"}, Orders_delivery_lookup, {"order_id"}, "Orders_delivery_lookup", JoinKind.LeftOuter),
				    #"Expanded Orders_delivery_lookup" = Table.ExpandTableColumn(#"Merged Queries1", "Orders_delivery_lookup", {"Delivery Status"}, {"Orders_delivery_lookup.Delivery Status"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Expanded Orders_delivery_lookup",{{"Orders_delivery_lookup.Delivery Status", "Delivery Status"}}),
				    #"Merged Queries2" = Table.NestedJoin(#"Renamed Columns1", {"order_id"}, Order_reviews_lookup, {"order_id"}, "Order_reviews_lookup", JoinKind.LeftOuter),
				    #"Expanded Order_reviews_lookup" = Table.ExpandTableColumn(#"Merged Queries2", "Order_reviews_lookup", {"Average Rating"}, {"Order_reviews_lookup.Average Rating"})
				in
				    #"Expanded Order_reviews_lookup"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

