table Order_reviews_lookup
	lineageTag: 05557076-8093-4a3d-92c4-adb803ad4c93

	column order_id
		dataType: string
		lineageTag: 40a40067-9872-4ac9-bf8e-48e7adf22297
		summarizeBy: none
		sourceColumn: order_id

		annotation SummarizationSetBy = Automatic

	column 'Average Rating'
		dataType: double
		lineageTag: 5619cfb4-8d57-490e-8a58-13923262e572
		summarizeBy: sum
		sourceColumn: Average Rating

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Order_reviews_lookup = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\NC\OneDrive\Desktop\Nexusgoods store capstone\Nexusgoods_order_reviews_dataset.csv"),[Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"review_id", type text}, {"order_id", type text}, {"review_score", Int64.Type}, {"review_comment_title", type text}, {"review_comment_message", type text}, {"review_creation_date", type text}, {"review_answer_timestamp", type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each true),
				    #"Grouped Rows" = Table.Group(#"Filtered Rows", {"order_id"}, {{"Average Rating", each List.Average([review_score]), type nullable number}})
				in
				    #"Grouped Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

